name: Test

on:
    push:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - dev
        paths:
            - "**.py"

jobs:
    build-and-deploy:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
                python-version: ["3.7", "3.8", "3.9", "3.10"]
        name: Testing with python ${{ matrix.python-version }} on ${{ matrix.os }}
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools wheel
                  python -m pip install poetry
                  poetry install

            - name: Setup Chrome
              uses: browser-actions/setup-chrome@v0.0.0
              if: startsWith(matrix.os, 'ubuntu')

            - name: Execute tests
              run: |
                  poetry run pytest tests -v
